name: maximegalon5
favicon: null
layout_spectrum: 0.45299411145970225
typography_spectrum: 0.7221479041036218
title: Epimethian
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7439514945726842
  lightness: 0.258272010833025
  saturation: 0.5799616100266576
  rhythmicContrast: 0.6090018071699888
purpose: []
